apiVersion: v1
kind: Service
metadata:
  name: mongodb-order
spec:
  clusterIP: None
  selector:
    app: mongodb-order
  ports:
    - name: mongodb-order
      protocol: TCP
      port: 27017
      targetPort: 27017
