apiVersion: v1
kind: Pod
metadata:
  name: arch
spec:
  containers:
  - name: arch
    image: ubuntu:latest
    # Just spin & wait forever
    command: [ "/bin/bash", "-c", "--" ]
    args: [ "while true; do sleep 30; done;" ]
