kind: ServiceAccount
apiVersion: v1
metadata:
  name: mongodb-stock-role
  namespace: default

---

apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: mongodb-stock-role
rules:
  - apiGroups: [""]
    resources: ["pods", "pods/log"]
    verbs: ["get", "list"]

---

apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: mongodb-stock-role
  namespace: default
subjects:
  - kind: ServiceAccount
    name: mongodb-stock-role
    namespace: default
roleRef:
  kind: ClusterRole
  name: mongodb-stock-role
  apiGroup: rbac.authorization.k8s.io
