apiVersion: v1
kind: Service
metadata:
  name: mongodb-stock-service
spec:
  clusterIP: None
  selector:
    app: mongodb-stock
  ports:
    - name: mongodb-stock
      protocol: TCP
      port: 27017
      targetPort: 27017

---

apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: mongodb-stock
spec:
  serviceName: mongodb-stock-service
  selector:
    matchLabels:
      app: mongodb-stock
  template:
    metadata:
      labels:
        app: mongodb-stock
    spec:
      serviceAccountName: mongodb-stock-role
      terminationGracePeriodSeconds: 10
      containers:
        # DATABASE CONTAINER
        - name: mongodb
          image: mongo
          env:
          - name: MONGO_INITDB_DATABASE
            value: stockdb
          ports:
            - containerPort: 27017
          volumeMounts:
            - name: mongodb-stock-pvc
              mountPath: /data/db
          # DEFINE CPU LIMITS (OPTIONAL)
          resources:
            requests:
              cpu: 0.1
              memory: 100Mi
        # SIDECAR CONTAINER
        - name: mongodb-stock-sidecar
          image: cvallance/mongo-k8s-sidecar
          env:
            - name: MONGO_SIDECAR_POD_LABELS
              value: "app=mongodb-stock"
  volumeClaimTemplates:
    - metadata:
        name: mongodb-stock-pvc
      spec:
        accessModes: ["ReadWriteOnce"]
        resources:
          requests:
            storage: 5Gi
