apiVersion: v1
kind: Service
metadata:
  name: stockdb-svc-2
spec:
  selector:
    app: stockdb-2
  ports:
    - name: stockdb-2
      port: 27217
      targetPort: 27217
  clusterIP: None

---

apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: stockdb-2
spec:
  serviceName: stockdb-svc-2
  replicas: 1
  selector:
    matchLabels:
      app: stockdb-2
  template:
    metadata:
      labels:
        app: stockdb-2
    spec:
      containers:
        - name: stockdb-2
          image: mongo:4.4
          imagePullPolicy: IfNotPresent
          ports:
          - containerPort: 27217
            name: stockdb2
          volumeMounts:
          - name: stockdb-pvc-2
            mountPath: /mnt/db
  volumeClaimTemplates:
  - metadata:
      name: stockdb-pvc-2
    spec:
      accessModes: [ "ReadWriteOnce" ]
        #      storageClassName: "stockdb-sc-2"
      resources:
        requests:
          storage: 1Gi

