apiVersion: v1
kind: Service
metadata:
  labels:
    app: mongodb-stock
  name: mongodb-stock
spec:
  ports:
  - port: 27017
    targetPort: 27017
  clusterIP: None
  selector:
    app: mongodb-stock
