apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  labels:
    app: mongodb-stock-claim0
  name: mongodb-stock-claim0
spec:
  accessModes:
  - ReadWriteOnce
  storageClassName: manual
  resources:
    requests:
      storage: 1Gi

---

apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: manual
provisioner: k8s.io/minikube-hostpath
reclaimPolicy: Retain
volumeBindingMode: Immediate
