apiVersion: v1
kind: Service
metadata:
  name: kafka-service
  labels:
    app: kafka-broker
      #namespace: kafka
spec:
  ports:
  - port: 9092
    targetPort: 9092
  selector:
    app: kafka-broker

---

apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: kafka-broker
  name: kafka-broker
    #namespace: kafka
spec:
  replicas: 1
  selector:
    matchLabels:
      app: kafka-broker
  template:
    metadata:
      labels:
        app: kafka-broker
    spec:
      hostname: kafka-broker
      containers:
      - env:
        - name: KAFKA_BROKER_ID
          value: "1"
        - name: KAFKA_ZOOKEEPER_CONNECT
          value: zookeeper-service
        - name: KAFKA_LISTENERS
          value: PLAINTEXT://:9092
        - name: KAFKA_ADVERTISED_LISTENERS
          value: PLAINTEXT://kafka-broker:9092
        - name: KAFKA_CREATE_TOPICS
          value: "stock-syn:1:1,stock-ack:1:1,payment-syn:1:1,payment-ack:1:1,order-syn:1:1,order-ack:1:1"
        image: wurstmeister/kafka
        imagePullPolicy: IfNotPresent
        name: kafka-broker
        ports:
        - containerPort: 9092
