apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: testmongoconnection-pvc
spec:
  accessModes: [ "ReadWriteOnce"  ]
  resources:
    requests:
      storage: 1Gi

---

apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: mongodb
spec:
  serviceName: mongodb-service
  replicas: 1
  selector:
    matchLabels:
      app: mongodb
  template:
    metadata:
      labels:
        app: mongodb
    spec:
      containers:
        - name: mongodb
          image: mongo:4.4
          ports:
            - containerPort: 27017
          volumeMounts:
            - name: mongodb-data
              mountPath: /data/db
  volumeClaimTemplates:
    - metadata:
        name: testmongoconnection-pvc

---

apiVersion: v1
kind: Service
metadata:
  name: mongodb-service
spec:
  selector:
    app: mongodb
  ports:
    - name: mongodb
      port: 27017
      targetPort: 27017
  clusterIP: None

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: go-app
spec:
  replicas: 5
  selector:
    matchLabels:
      app: go-app
  template:
    metadata:
      labels:
        app: go-app
    spec:
      containers:
        - name: go-app
          image: testmongoconnection:latest
          imagePullPolicy: Never
          ports:
            - containerPort: 5000
